apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: url-shortener
data:
  HTTP_ADDR: ":8000"
  LOG_ENABLED: "true"
  PROFILING_ENABLED: "false"
  PROFILING_ADDR: "127.0.0.1:6060"
  PROFILING_RUNTIME_STATS_ENABLED: "true"
  PROFILING_RUNTIME_STATS_INTERVAL: "15s"
  REQUEST_TIMEOUT: "2s"
  READ_TIMEOUT: "15s"
  WRITE_TIMEOUT: "15s"
  IDLE_TIMEOUT: "60s"
  CORS_ALLOW_ORIGIN: "*"
  DB_MAX_CONNS: "10"
  DB_MIN_CONNS: "2"
  REDIS_ENABLED: "true"
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
  REDIS_TTL: "24h"
  REDIS_DIAL_TIMEOUT: "2s"
  REDIS_READ_TIMEOUT: "500ms"
  REDIS_WRITE_TIMEOUT: "500ms"
  CB_MAX_REQUESTS: "3"
  CB_INTERVAL: "30s"
  CB_TIMEOUT: "10s"
  CB_MIN_REQUESTS: "5"
  CB_FAILURE_RATIO: "0.6"
